version: '3.8'

services:
  transcription-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=cascade_oVWHSgVFcGVZKmIWOWKXQDPSEILVkGYBJVPDCuODQEk
      - TZ=America/Sao_Paulo
      - WHISPER_MODEL=tiny
      - PROJECT_NAME=Video Transcription API
      - VERSION=1.0.0
      - PYTHONPATH=/opt/transcricao-whisper-v1/Transcricao
    volumes:
      - /opt/transcricao-whisper-v1/credentials.json:/opt/transcricao-whisper-v1/Transcricao/credentials.json:ro
      - /opt/transcricao-whisper-v1/token.json:/opt/transcricao-whisper-v1/Transcricao/token.json
      - /opt/transcricao-whisper-v1/temp:/opt/transcricao-whisper-v1/Transcricao/temp
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 4G
          cpus: '2'
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  default:
    driver: overlay
    attachable: true