version: '3.8'

services:
  transcription-api:
    image: transcricao-whisper:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcription-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=cascade_oVWHSgVFcGVZKmIWOWKXQDPSEILVkGYBJVPDCuODQEk
      - TZ=America/Sao_Paulo
      - WHISPER_MODEL=tiny
      - PROJECT_NAME="Video Transcription API"
      - VERSION="1.0.0"
    volumes:
      - /opt/transcricao-whisper-v1/credentials.json:/opt/transcricao-whisper-v1/Transcricao/credentials.json:ro
      - /opt/transcricao-whisper-v1/token.json:/opt/transcricao-whisper-v1/Transcricao/token.json
      - /opt/transcricao-whisper-v1/temp:/opt/transcricao-whisper-v1/Transcricao/temp
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    driver: bridge
