version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
    environment:
      - API_KEY=${API_KEY}
    restart: unless-stopped

  # Descomente se quiser usar o frontend
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_APP_API_URL=http://api:8000
  #   depends_on:
  #     - api
