version: '3.8'

services:
  transcription-api:
    image: python:3.11-slim
    working_dir: /app
    command: >
      sh -c "apt-get update && 
             apt-get install -y git ffmpeg curl &&
             git clone https://github.com/jsKahne/Convert-to-audio.git /tmp/transcription &&
             cp -r /tmp/transcription/* /app/ &&
             rm -rf /tmp/transcription &&
             pip install -r requirements.txt &&
             python main.py"
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - TZ=America/Sao_Paulo
      - WHISPER_MODEL=base
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
      - ./temp:/app/temp
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    driver: overlay
