version: '3.8'

services:
  transcription-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=cascade_oVWHSgVFcGVZKmIWOWKXQDPSEILVkGYBJVPDCuODQEk
      - TZ=America/Sao_Paulo
      - WHISPER_MODEL=base
    volumes:
      - /opt/transcricao-whisper-v1/credentials.json:/app/credentials.json:ro
      - /opt/transcricao-whisper-v1/token.json:/app/token.json
      - /opt/transcricao-whisper-v1/temp:/app/temp
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    driver: overlay